### ISSUE TITLE
データの詳細のドキュメントへのリンクを付与

### ISSUE THREAD

**Issue by kntoshiya** [MIERUNE/qgis-jaxa-earth-plugin#13]
## 期限

- 5/15まで

## 経緯

- タイトルのとおり

## 方針

- xxxx

## 関連するファイル

- 特になし

**Comment by bordoray** [comment]
URL構成
https://data.earth.jaxa.jp/en/datasets/#/id/{dataset_name (named as key)}
https://data.earth.jaxa.jp/en/datasets/#/id/JAXA.EORC_GSMaP_standard.Gauge.00Z-23Z.v6_half-monthly-normal
