### ISSUE TITLE
UI layout is broken on MacOS

### ISSUE THREAD

**Issue by dayjournal** [MIERUNE/qgis-jaxa-earth-plugin#28]
It is different from the UI layout shown in the README.

<img width="1581" alt="スクリーンショット 2024-05-29 23 16 26" src="https://github.com/MIERUNE/qgis-jaxa-earth-plugin/assets/7871642/2ab5270e-7e55-4df7-9420-bb7266c1b974">

**Comment by bordoray** [comment]
Will be fixed on next release:
- UI changed to dialog on #17 
- Readme to be updated on end May/early June.

**Comment by bordoray** [comment]
Solved with release 2.0.0
