### ISSUE TITLE
JAXA Earth API for Python version updated

### ISSUE THREAD

**Issue by dayjournal** [MIERUNE/qgis-jaxa-earth-plugin#5]
Hi, The JAXA Earth API for Python version seems to have been updated to 0.1.2. Is there any plan to update this plugin as well?

https://data.earth.jaxa.jp/api/python/rnotes.html#version-0-1-2-prototype

![スクリーンショット 2022-09-12 17 34 41](https://user-images.githubusercontent.com/7871642/189609067-b54b1109-9a06-4565-ac36-959448f19b34.png)

**Comment by Kanahiro** [comment]
Thank you for a good news, if it is easy to migrate we should include new version of JAXA Earth API for Python.
We'll try to migrate and confirm it will work or not. @satoshi7190 Could you try it?

**Comment by Kanahiro** [comment]
Tips:

JAXA Earth API for Python module is included as a static folder.
https://github.com/MIERUNE/qgis-jaxa-earth-plugin/tree/master/jaxa/earth

I added one methods to `ImageProcess` class.
https://github.com/MIERUNE/qgis-jaxa-earth-plugin/blob/943c0ee65714a8832833957b7b8fe1f08cf57aa0/jaxa/earth/je.py#L992
